type CatalogLocale = 'CH' | 'EN'

const COPY: Readonly<Record<CatalogLocale, Readonly<Record<string, string>>>> = {
  CH: {
    list: '列表',
    selectEntry: '选择数据',
    close: '关闭',
    filterRarity: '稀有度',
    filterCategory: '分类',
    filterElement: '属性',
    filterProfession: '职业',
    filterWeapon: '武器',
    filterType: '类型',
    filterSummary: '筛选',
    filterSummaryCount: '筛选（{count}）',
    overviewCount: '{count} 条数据',
    overviewHint: '选择卡片查看完整数据',
    versionChanges: '版本差异',
    variants: '{count} 个变体',
    rarityFact: '{count} 星',
    equipmentCount: '{count} 件装备',
    achievementCount: '{count} 个奖章',
    groupCount: '{count} 个分组',
    platedCount: '{count} 个可镀层',
    equipmentSets: '装备套装',
    independentEquipment: '独立装备',
    achievementCategories: '奖章分类',
    added: '新增',
    modified: '修改',
    tools: '数据工具',
    before: '变更前',
    after: '变更后',
    removed: '已移除',
    changed: '已变更',
    copyData: '复制数据',
    expandAll: '展开全部等级',
    collapse: '收起',
    expand: '展开',
    level: '等级',
    name: '名称',
    description: '说明',
    parameters: '参数',
    cooldown: '冷却时间',
    skillCost: '技能消耗',
    materials: '材料',
    developmentCost: '养成材料',
    characterHeader: '角色信息',
    attributeGrowth: '属性成长',
    talents: '天赋',
    potentials: '潜能',
    attributeNodes: '属性节点',
    skills: '技能',
    logisticsSkills: '后勤技能',
    potentialImages: '潜能立绘',
    profile: '档案',
    voiceRecords: '语音记录',
    profession: '职业',
    weapon: '武器类型',
    element: '属性',
    mainAttribute: '主属性',
    subAttribute: '副属性',
    voiceActor: '配音',
    basicAttack: '普通攻击',
    combatSkill: '战技',
    comboSkill: '连携技',
    ultimate: '终结技',
    weaponHeader: '武器信息',
    baseAttack: '基础攻击力',
    attack: '攻击力',
    skillData: '技能数据',
    breakthroughMaterials: '突破材料',
    breakthroughLevel: '突破 {level}',
    initial: '初始',
    gold: '金币',
    skillBounds: '技能 {skill}: {lower}-{upper}',
    potentialLevel: '潜能 {level}',
    skillUpperBound: '技能 {skill} 上限 {upper}',
    story: '故事',
    enemyHeader: '敌人信息',
    abilities: '能力说明',
    poiseBreakBuffs: '失衡效果',
    variantAttributes: '变体属性',
    baseVariant: '基础变体',
    template: '属性模板',
    modifiers: '属性修正',
    buffs: '增益',
    differences: '相较基础变体',
    hp: '生命值',
    defense: '防御力',
    dangerous: '危险',
    globalEffect: '全局效果',
    pinnedHealthBar: '固定生命条',
    initialSuperArmor: '初始霸体',
    zeroPoiseSuperArmor: '失衡时霸体',
    superArmorWhenResilienceZero: '韧性归零霸体',
    breakingAttackedAtbObtain: '破韧受击 ATB',
    attackValueAgainstTower: '对塔攻击值',
    maxResilience: '最大韧性',
    pushedBackCoefficient: '击退系数',
    resilienceDecreaseWhenHurt: '受击韧性削减',
    resilienceFullRecoverTime: '韧性完全恢复时间',
    resilienceRecover: '韧性恢复量',
    resilienceRecoverInterval: '韧性恢复间隔',
    poiseKnotPct: '失衡节点比例',
    equipHeader: '套装信息',
    setSkills: '套装技能',
    setPieces: '套装部件',
    enhancementInfo: '强化信息',
    partArmor: '护甲',
    partGloves: '手套',
    partAccessory: '配件',
    minimumLevel: '等级 {level}',
    craftingCost: '制造消耗',
    enhancementGuarantee: '强化保底',
    base: '基础',
    stat: '属性',
    maximumCraftingCount: '制造数量上限',
    recyclingReturnRate: '回收返还率',
    maximumEnhancementLevel: '最高强化 +{level}',
    materialsConsumed: '消耗材料',
    materialsReturned: '返还材料',
    itemHeader: '物品信息',
    useEffects: '使用效果',
    afterUse: '使用后',
    afterEquip: '装备后',
    duration: '持续时间',
    useCount: '使用次数',
    castTime: '施放时间',
    recoverCount: '恢复次数',
    recoveryInterval: '恢复间隔',
    properties: '物品属性',
    maxStack: '堆叠上限',
    backpackStackLimit: '背包堆叠上限',
    storageSpace: '仓储空间',
    craftingPaths: '制造路径',
    recipeSources: '获取来源',
    recipeUses: '用途',
    noMaterials: '无需材料',
    notConfigured: '未配置',
    facilityLevel: '设施等级 {level}',
    integratedIndustry: '集成工业',
    manualCrafting: '手工制造',
    hubManufacturing: '枢纽制造',
    equipmentManufacturing: '装备制造',
    growCabinPlanting: '培育舱种植',
    growCabinSeedCollection: '培育舱采种',
    spaceshipManufacturing: '基建制造',
    obtainWays: '获取方式',
    applicableWeapons: '适用武器',
    choiceBoxContents: '选择箱内容',
    selectableCount: '可选择 {count} 项',
    iconComposite: '图标合成',
    iconTransformType: '图标变换类型',
    showRarity: '显示稀有度',
    markIcon: '标记图标',
    displayType: '展示分类',
    encyclopediaEntry: '百科条目',
    entryId: '条目 ID',
    encyclopediaGroup: '百科分组',
    yes: '是',
    no: '否',
    achievementHeader: '奖章分类',
    achievementGroups: '奖章列表',
    defaultGroup: '其他奖章',
    upgradable: '可升级',
    platable: '可镀层',
    rareEffect: '稀有效果',
    hiddenUntilObtained: '获得前隐藏',
    achievementLevel: '{level} 级',
    progress: '进度 {value}',
    daysShort: '天',
    hoursShort: '小时',
    minutesShort: '分',
    secondsShort: '秒',
    lessThanSecond: '小于 1 秒'
  },
  EN: {
    list: 'List',
    selectEntry: 'Select data',
    close: 'Close',
    filterRarity: 'Rarity',
    filterCategory: 'Category',
    filterElement: 'Element',
    filterProfession: 'Profession',
    filterWeapon: 'Weapon',
    filterType: 'Type',
    filterSummary: 'Filters',
    filterSummaryCount: 'Filters ({count})',
    overviewCount: '{count} records',
    overviewHint: 'Select a card to view complete data',
    versionChanges: 'Version changes',
    variants: '{count} variants',
    rarityFact: '{count} stars',
    equipmentCount: '{count} pieces',
    achievementCount: '{count} achievements',
    groupCount: '{count} groups',
    platedCount: '{count} platable',
    equipmentSets: 'Equipment sets',
    independentEquipment: 'Independent equipment',
    achievementCategories: 'Achievement categories',
    added: 'Added',
    modified: 'Modified',
    tools: 'Data tools',
    before: 'Before',
    after: 'After',
    removed: 'Removed',
    changed: 'Changed',
    copyData: 'Copy data',
    expandAll: 'Expand all levels',
    collapse: 'Collapse',
    expand: 'Expand',
    level: 'Level',
    name: 'Name',
    description: 'Description',
    parameters: 'Parameters',
    cooldown: 'Cooldown',
    skillCost: 'Skill cost',
    materials: 'Materials',
    developmentCost: 'Development materials',
    characterHeader: 'Character information',
    attributeGrowth: 'Attribute growth',
    talents: 'Talents',
    potentials: 'Potentials',
    attributeNodes: 'Attribute nodes',
    skills: 'Skills',
    logisticsSkills: 'Logistics skills',
    potentialImages: 'Potential images',
    profile: 'Profile',
    voiceRecords: 'Voice records',
    profession: 'Profession',
    weapon: 'Weapon type',
    element: 'Element',
    mainAttribute: 'Main attribute',
    subAttribute: 'Sub attribute',
    voiceActor: 'Voice actor',
    basicAttack: 'Basic attack',
    combatSkill: 'Combat skill',
    comboSkill: 'Combo skill',
    ultimate: 'Ultimate',
    weaponHeader: 'Weapon information',
    baseAttack: 'Base attack',
    attack: 'Attack',
    skillData: 'Skill data',
    breakthroughMaterials: 'Breakthrough materials',
    breakthroughLevel: 'Breakthrough {level}',
    initial: 'Initial',
    gold: 'Gold',
    skillBounds: 'Skill {skill}: {lower}-{upper}',
    potentialLevel: 'Potential {level}',
    skillUpperBound: 'Skill {skill} cap {upper}',
    story: 'Story',
    enemyHeader: 'Enemy information',
    abilities: 'Abilities',
    poiseBreakBuffs: 'Poise-break effects',
    variantAttributes: 'Variant attributes',
    baseVariant: 'Base variant',
    template: 'Attribute template',
    modifiers: 'Modifiers',
    buffs: 'Buffs',
    differences: 'Compared with base variant',
    hp: 'HP',
    defense: 'Defense',
    dangerous: 'Dangerous',
    globalEffect: 'Global effect',
    pinnedHealthBar: 'Pinned health bar',
    initialSuperArmor: 'Initial super armor',
    zeroPoiseSuperArmor: 'Zero-poise super armor',
    superArmorWhenResilienceZero: 'Super armor at zero resilience',
    breakingAttackedAtbObtain: 'Break-hit ATB gain',
    attackValueAgainstTower: 'Attack against tower',
    maxResilience: 'Max resilience',
    pushedBackCoefficient: 'Push-back coefficient',
    resilienceDecreaseWhenHurt: 'Resilience loss when hit',
    resilienceFullRecoverTime: 'Full resilience recovery time',
    resilienceRecover: 'Resilience recovery',
    resilienceRecoverInterval: 'Resilience recovery interval',
    poiseKnotPct: 'Poise knot ratio',
    equipHeader: 'Set information',
    setSkills: 'Set skills',
    setPieces: 'Set pieces',
    enhancementInfo: 'Enhancement information',
    partArmor: 'Armor',
    partGloves: 'Gloves',
    partAccessory: 'Accessory',
    minimumLevel: 'Level {level}',
    craftingCost: 'Crafting cost',
    enhancementGuarantee: 'Enhancement guarantee',
    base: 'Base',
    stat: 'Stat',
    maximumCraftingCount: 'Maximum crafting count',
    recyclingReturnRate: 'Recycling return rate',
    maximumEnhancementLevel: 'Maximum enhancement +{level}',
    materialsConsumed: 'Materials consumed',
    materialsReturned: 'Materials returned',
    itemHeader: 'Item information',
    useEffects: 'Use effects',
    afterUse: 'After use',
    afterEquip: 'After equip',
    duration: 'Duration',
    useCount: 'Use count',
    castTime: 'Cast time',
    recoverCount: 'Recovery count',
    recoveryInterval: 'Recovery interval',
    properties: 'Item properties',
    maxStack: 'Maximum stack',
    backpackStackLimit: 'Backpack stack limit',
    storageSpace: 'Storage space',
    craftingPaths: 'Crafting paths',
    recipeSources: 'Sources',
    recipeUses: 'Uses',
    noMaterials: 'No materials required',
    notConfigured: 'Not configured',
    facilityLevel: 'Facility level {level}',
    integratedIndustry: 'Integrated industry',
    manualCrafting: 'Manual crafting',
    hubManufacturing: 'Hub manufacturing',
    equipmentManufacturing: 'Equipment manufacturing',
    growCabinPlanting: 'Grow-cabin planting',
    growCabinSeedCollection: 'Grow-cabin seed collection',
    spaceshipManufacturing: 'Spaceship manufacturing',
    obtainWays: 'Obtain ways',
    applicableWeapons: 'Applicable weapons',
    choiceBoxContents: 'Choice box contents',
    selectableCount: 'Select {count}',
    iconComposite: 'Icon composite',
    iconTransformType: 'Icon transform type',
    showRarity: 'Show rarity',
    markIcon: 'Mark icon',
    displayType: 'Display type',
    encyclopediaEntry: 'Encyclopedia entry',
    entryId: 'Entry ID',
    encyclopediaGroup: 'Encyclopedia group',
    yes: 'Yes',
    no: 'No',
    achievementHeader: 'Achievement category',
    achievementGroups: 'Achievements',
    defaultGroup: 'Other achievements',
    upgradable: 'Upgradable',
    platable: 'Platable',
    rareEffect: 'Rare effect',
    hiddenUntilObtained: 'Hidden until obtained',
    achievementLevel: 'Level {level}',
    progress: 'Progress {value}',
    daysShort: 'd',
    hoursShort: 'h',
    minutesShort: 'm',
    secondsShort: 's',
    lessThanSecond: 'less than 1s'
  }
}

function interpolate(template: string, variables: Readonly<Record<string, string | number>>): string {
  return template.replace(/\{([^}]+)\}/g, (match, key: string) =>
    variables[key] === undefined ? match : String(variables[key])
  )
}

export function catalogUiText(
  locale: string,
  key: string,
  variables: Readonly<Record<string, string | number>> = {}
): string {
  const language: CatalogLocale = locale === 'EN' ? 'EN' : 'CH'
  return interpolate(COPY[language][key] ?? COPY.EN[key] ?? key, variables)
}
