import type { AppLocale } from '@ake/r2-contract'

const EN = {
  title: 'Contingency Contract',
  description: 'Configure contract terms and inspect their live combat effects.',
  search: 'Search contracts',
  loading: 'Loading contingency contracts',
  select: 'Select contract',
  noMatches: 'No matching contracts',
  loadFailed: 'Contingency Contract data could not be loaded',
  'overview.title': 'Contingency Contracts',
  'overview.description': 'Choose an activity to configure terms, rewards, enemies, shops, and tasks.',
  'statuses.active': 'Active',
  'statuses.upcoming': 'Upcoming',
  'statuses.ended': 'Ended',
  'statuses.permanent': 'Permanent',
  'counts.indicatorGroups': '{count} indicator groups',
  'counts.terms': '{count} terms',
  'sections.activityConfiguration': 'Activity Configuration',
  'sections.contractTerms': 'Contract Terms',
  'sections.selectedTermDetails': 'Selected Term Details',
  'sections.dungeonEnemies': 'Dungeon Enemies',
  'sections.levelRewards': 'Level Rewards',
  'sections.shop': 'Shop',
  'sections.tasks': 'Tasks',
  'activityInfo.activityId': 'Activity ID',
  'activityInfo.gameplayType': 'Gameplay type',
  'activityInfo.stageId': 'Gameplay end stage',
  'activityInfo.maxTagColumns': 'Maximum tag columns',
  'activityInfo.currencyAmount': 'Comparison currency',
  'activityInfo.shopGroup': 'Shop group',
  'contract.group': 'Group {id}',
  'contract.key': 'Key {key}',
  'contract.requires': 'Requires {key}',
  'contract.conflict': 'Conflict {conflict}',
  'contract.conflictWith': 'Conflict {conflict}: {tag}',
  'contract.previewUnavailable': 'Preview unavailable',
  'contract.toggle': 'Toggle {name}',
  'conflicts.tagMissing': 'This term is unavailable.',
  'conflicts.withTag': 'Conflicts with {tag} ({conflict}).',
  'conflicts.missingKeys': 'Requires keys: {keys}.',
  'score.label': 'Selected score',
  'score.selected': '{count} selected',
  'score.reset': 'Reset',
  'termTypes.enemyBuff': 'Enemy buff',
  'termTypes.selfDebuff': 'Squad debuff',
  'termTypes.timeReduction': 'Time reduction',
  'termTypes.none': 'Other effect',
  'empty.selected': 'No terms selected',
  'empty.enemies': 'No dungeon enemy data',
  'empty.rewards': 'No level rewards',
  'empty.shop': 'No shop configured',
  'empty.tasks': 'No tasks configured',
  'dungeon.level': 'Level {level}',
  'dungeon.count': 'x{count}',
  'dungeon.recommended': 'Recommended level {level}',
  'dungeon.waves': '{count} waves',
  'dungeon.wave': 'Wave {id}',
  'dungeon.enemyCount': '{count} enemies',
  'dungeon.runtime': 'Runtime data',
  'dungeon.levelData': 'Level data',
  'dungeon.spawner': 'Spawner',
  'dungeon.levelScript': 'LevelScript',
  'dungeon.available': 'available',
  'dungeon.unavailable': 'unavailable',
  'dungeon.attribute': 'Attribute',
  'dungeon.baseValue': 'Base',
  'dungeon.currentValue': 'Current',
  'dungeon.buffs': 'Buffs: {ids}',
  'enemyFlags.dangerous': 'Dangerous',
  'enemyFlags.globalEffect': 'Global effect',
  'enemyFlags.pinnedHealthBar': 'Pinned health bar',
  'rewards.level': 'Lv.{level}',
  'rewards.scoreLevel': 'Score {score} reaches level {level}: {rewards}',
  'rewards.allCompletedLevel': 'Complete all objectives for level {level}: {rewards}',
  'rewards.none': 'No reward items',
  'rewards.separator': ', ',
  'shop.title': 'Shop: {name}',
  'shop.goodsCount': '{count} goods',
  'shop.item': 'Item',
  'shop.price': 'Price',
  'shop.limit': 'Limit',
  'shop.unlimited': 'Unlimited',
  'shop.discount': '{percent}% off',
  'tasks.count': '{count} tasks',
  'tasks.updatable': 'Updatable',
  'tasks.rewards': 'Rewards',
  'tasks.empty': 'No tasks in this group',
  'detail.subtitle': '{activityId} · {gameId}',
  'directory.aria': 'Contingency Contract activities',
  'overview.aria': 'Contract status overview',
  'common.close': 'Close',
  'common.retry': 'Retry'
} as const

const CH: Record<keyof typeof EN, string> = {
  title: '危机合约',
  description: '配置合约条款并查看实时战斗影响。',
  search: '搜索合约',
  loading: '正在加载危机合约',
  select: '选择合约',
  noMatches: '没有匹配的合约',
  loadFailed: '无法加载危机合约数据',
  'overview.title': '危机合约',
  'overview.description': '选择活动以配置条款，并查看奖励、敌人、商店和任务。',
  'statuses.active': '进行中',
  'statuses.upcoming': '即将开始',
  'statuses.ended': '已结束',
  'statuses.permanent': '常驻',
  'counts.indicatorGroups': '{count} 个指标组',
  'counts.terms': '{count} 个条款',
  'sections.activityConfiguration': '活动配置',
  'sections.contractTerms': '合约条款',
  'sections.selectedTermDetails': '已选条款详情',
  'sections.dungeonEnemies': '副本敌人',
  'sections.levelRewards': '等级奖励',
  'sections.shop': '商店',
  'sections.tasks': '任务',
  'activityInfo.activityId': '活动 ID',
  'activityInfo.gameplayType': '玩法类型',
  'activityInfo.stageId': '玩法结束关卡',
  'activityInfo.maxTagColumns': '最大条款列数',
  'activityInfo.currencyAmount': '对比货币数量',
  'activityInfo.shopGroup': '商店组',
  'contract.group': '条款组 {id}',
  'contract.key': '钥匙 {key}',
  'contract.requires': '需要 {key}',
  'contract.conflict': '冲突组 {conflict}',
  'contract.conflictWith': '冲突组 {conflict}：{tag}',
  'contract.previewUnavailable': '不可预览',
  'contract.toggle': '切换条款 {name}',
  'conflicts.tagMissing': '该条款不可用。',
  'conflicts.withTag': '与 {tag} 冲突（{conflict}）。',
  'conflicts.missingKeys': '需要钥匙：{keys}。',
  'score.label': '已选分数',
  'score.selected': '已选择 {count} 个',
  'score.reset': '重置',
  'termTypes.enemyBuff': '敌方增益',
  'termTypes.selfDebuff': '我方减益',
  'termTypes.timeReduction': '时间缩减',
  'termTypes.none': '其他效果',
  'empty.selected': '尚未选择条款',
  'empty.enemies': '没有副本敌人数据',
  'empty.rewards': '没有等级奖励',
  'empty.shop': '没有配置商店',
  'empty.tasks': '没有配置任务',
  'dungeon.level': '等级 {level}',
  'dungeon.count': '×{count}',
  'dungeon.recommended': '推荐等级 {level}',
  'dungeon.waves': '{count} 个波次',
  'dungeon.wave': '波次 {id}',
  'dungeon.enemyCount': '{count} 名敌人',
  'dungeon.runtime': '运行时数据',
  'dungeon.levelData': '关卡数据',
  'dungeon.spawner': '生成器',
  'dungeon.levelScript': '关卡脚本',
  'dungeon.available': '可用',
  'dungeon.unavailable': '不可用',
  'dungeon.attribute': '属性',
  'dungeon.baseValue': '基础值',
  'dungeon.currentValue': '当前值',
  'dungeon.buffs': '增益：{ids}',
  'enemyFlags.dangerous': '危险敌人',
  'enemyFlags.globalEffect': '全局特效',
  'enemyFlags.pinnedHealthBar': '固定血条',
  'rewards.level': 'Lv.{level}',
  'rewards.scoreLevel': '分数达到 {score} 可升至 {level} 级：{rewards}',
  'rewards.allCompletedLevel': '完成全部目标可升至 {level} 级：{rewards}',
  'rewards.none': '无奖励物品',
  'rewards.separator': '、',
  'shop.title': '商店：{name}',
  'shop.goodsCount': '{count} 件商品',
  'shop.item': '物品',
  'shop.price': '价格',
  'shop.limit': '限购',
  'shop.unlimited': '不限',
  'shop.discount': '减免 {percent}%',
  'tasks.count': '{count} 个任务',
  'tasks.updatable': '可更新',
  'tasks.rewards': '奖励',
  'tasks.empty': '此分组没有任务',
  'detail.subtitle': '{activityId} · {gameId}',
  'directory.aria': '危机合约活动',
  'overview.aria': '合约状态概览',
  'common.close': '关闭',
  'common.retry': '重试'
}

export type CcCopyKey = keyof typeof EN

function interpolate(template: string, params: Readonly<Record<string, string | number>>): string {
  return template.replace(/\{([^}]+)\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : match
  )
}

export function ccCopy(
  locale: AppLocale,
  key: CcCopyKey,
  params: Readonly<Record<string, string | number>> = {}
): string {
  return interpolate(locale === 'CH' || locale === 'TC' ? CH[key] : EN[key], params)
}
